- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Init Lago env
      command:
        lago init LagoInitFile.yml
      args:
        creates: .lago/default/uuid
    - name: Remove user defined settigns from inventory
      blockinfile:
        path: "{{ inventory_file }}"
        marker: "# {mark} CUSTOM SETTINGS"
        state: absent
    - name: Create Ansible Hosts file from Lago env
      shell: lago ansible_hosts >> "{{ inventory_file }}"
    - name: Normalize inventory file
      replace:
        path: "{{ inventory_file }}"
        regexp: 'groups=(.*)'
        replace: '\1'
    - name: Refresh inventory
      meta: refresh_inventory
    - name: Start Lago env
      command: lago start

- hosts: all
  any_errors_fatal: True
  gather_facts: no
  tasks:
    - name: Wait for ssh
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        delay: 10
      delegate_to: localhost
      connection: local

- hosts: node0
  tasks:
    - name: Mark node0 as infra
      set_fact:
        openshift_node_labels:
          region: infra
          zone: default

- include: deploy-openshift.yml
  when: cluster_type is not defined or cluster_type == "openshift"

- include: deploy-kubernetes.yml
  when: cluster_type is defined and cluster_type == "kubernetes"
