---
- name: set SELinux to permissive mode
  command: setenforce 1

- name: set SELinux to permissive mode under configuration file
  selinux:
    policy: targeted
    state: enforcing

- name: stop and disable firewalld
  register: result
  service:
    state: stopped
    enabled: no
    name: firewalld
  failed_when: "result|failed and not 'Could not find the requested service' in result.msg"

- name: install epel repository
  yum:
    name: "{{ epel_repo_rpm }}"
    state: present

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openshift_packages }}"

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
