- name: Get Openshift version
  oc_version:
    kubeconfig: "{{ kconfig }}"
  register: oc_version

- name: Normalize kubevirt.yaml
  set_fact:
    normalized_mf: "{{ kubevirt_mf | mf_to_dict }}"

- name: Create project
  oc_project:
    name: "{{ project }}"
    kubeconfig: "{{ kconfig }}"
    state: "{{ state }}"

- name: RBAC
  include: "oc_obj_task.yml"
  loop_control:
    loop_var: kind
  with_items:
    - ServiceAccount
    - ClusterRole
    - ClusterRoleBinding

- name: Create scc
  oc_adm_policy_user:
    resource_kind: scc
    resource_name: privileged
    user: "system:serviceaccount:{{ project }}:{{ item }}"
    kubeconfig: "{{ kconfig }}"
    state: "{{ state }}"
  with_items:
    - kubevirt-privileged

- name: Create CustomResourceDefinition
  shell: |
    oc get "{{ item.name }}" || \
    echo "{{ item.manifest | to_yaml }}" | oc create -f -
  with_items: "{{ normalized_mf.CustomResourceDefinition }}"

- name: Create kubevirt's pods
  include: "oc_obj_task.yml"
  loop_control:
    loop_var: kind
  with_items:
    - Deployment
    - DaemonSet
